### PR TITLE
New version: 1.0.0

### PR DESCRIPTION
**Pull request by thecodeassassin**
@danibrutal @CentaurWarchief  please review version 1.0.0

* Removed support for php 5.3, php 5.4
* Upgraded to new guzzle bundle
* Added UDP support
* Allow for pluggable drivers

### CODE REVIEW

**Comment by thecodeassassin** [comment]
@danibrutal please review this when you have the time

**Comment by CentaurWarchief** [comment]
@thecodeassassin 

https://github.com/influxdb/influxdb-php/blob/c2bd3c4a79217b124113111321452bdf334cf9ba/src/InfluxDB/Database.php#L148. This is totally weird. First we `selectDB` and then ask if it exists?

I suggest a method: `databaseExists($name)` [here](https://github.com/influxdb/influxdb-php/blob/c2bd3c4a79217b124113111321452bdf334cf9ba/src/InfluxDB/Client.php).

**Comment by thecodeassassin** [comment]
I see your point, but this allows for a logical flow:

```
  // check if a database exists then create it if it doesn't
    $database = $client->selectDB('test_db');
    
    if (!$database->exists()) {
        $database->create(new RetentionPolicy('test', '1d', 2, true));
    } 
```

I would like to keep it like this.

**Comment by CentaurWarchief** [comment]
In this case we can improve it. We can only create something that doesn't exists, sure? (in database context). So:

```
<?php

class InexistentDatabase implements DatabaseInterface
{
    public function __construct(Client $influx, $name, DriverInterface $driver)
    {
        $this->influx = $influx;
        $this->name   = (string) $name;
        $this->driver = $driver;
    }

    /**
     * @return Database
     * @throws UnableToCreateDatabaseException
     */
    public function create()
    {
        if (! $this->influx->createDatabase($this->name)) {
            throw new UnableToCreateDatabaseException();
        }

        return new Database($this->name, $this->driver);
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->name;
    }

    public function query()
    {
        throw new \BadMethodCallException('Unable to perform queries in a inexistent database');
    }

    // ...
}
```

`Client#selectDB` may return `InexistentDatabase` (which could be turned into Database, which is an existent one) &mdash; or simply Database.

**Comment by thecodeassassin** [comment]
I really appreciate the effort here, truly i do. However this is a little bit too much abstraction and i want to keep the library relatively simple and straightforward. We are already doing a lot more abstractions that the python library and i feel that if we go down this road we will make the library unnecessarily complex.

**Comment by CentaurWarchief** [comment]
> Simplicity does not precede complexity, but follows it &mdash; Alan Perlis.

That's the point. The API will be the same for who is using. And plus a good design. We shouldn't care if python library is doing or not some abstractions, we should care about our code and keep the good API. What happens under the hood is up to us exclusively. Don't you agree?

Anyway, that's enuff. Let's keep it \`simple\` the way it is now. I do agree with you, we should always put it on a balance, but I don't agree that some abstractions makes the whole thing more complex or even that they're unnecessary.

**Comment by thecodeassassin** [comment]
Exactly my point, i like abstractions in the right places. Maybe i saw your suggestion out of context, i don't know. All i want to avoid is a Zend Framework 2 fiasco where potential contributors get confused by unnecessarily overcomplicated  abstractions.

**Comment by CentaurWarchief** [comment]
Yeah, I understand. But I can't speak for that ones in ZF2. In this specific case I don't see any overcomplicated stuff instead of benefits and a good design. 

Ha, and I'd say that this is one of the top royal reasons for poor code and bug introduction. You think that you're doing something simple for the user whereas you're maintaining stuff that shouldn't be here and also you meet yourself fighting against your own code. What a situation, huh?

As the quote said before, there's always something big behind your simplicity. Google's page is a example, just a search bar, try look under the hood &mdash; how many things are handled just to provide that simplicity.

What I want with all this discussion is to make your think when you're thinking in design, thinking in something that does makes sense and understand that simple difference.

:+1: :100:

**Pull request merged**
